import React, { useState, useRef } from 'react';
import { useAppStore } from '../../store/useAppStore';
import { generateBrief } from '../../services/llm';
import { getModelById } from '../../config/models';
import { KEYWORD_GROUP_LABELS, KEYWORD_GROUP_ICONS, VOLUME_LABELS } from '../../types';
import type { AppError, KeywordProposal } from '../../types';

const GROUP_COLORS: Record<KeywordProposal['group'], { bg: string; color: string }> = {
    semantic: { bg: 'var(--blue-soft)', color: 'var(--blue)' },
    synonyms: { bg: 'var(--purple-soft)', color: 'var(--purple)' },
    volume: { bg: 'var(--green-soft)', color: 'var(--green)' },
    llm: { bg: 'var(--amber-soft)', color: 'var(--amber)' },
};

export const KeywordSelection: React.FC = () => {
    const {
        keywordProposals, toggleKeyword, selectAllKeywords, deselectAllKeywords,
        selectGroup, deselectGroup, config, prevStep,
        setBrief, setLoading, setStreaming, setError, setStep: goToStep,
        isLoading, error, addToHistory
    } = useAppStore();

    const [collapsedGroups, setCollapsedGroups] = useState<Set<string>>(new Set());
    const [warningShown, setWarningShown] = useState(false);
    const abortRef = useRef<AbortController | null>(null);
    const model = getModelById(config.modelId);

    const selectedCount = keywordProposals.filter((kw) => kw.selected).length;

    const groups: KeywordProposal['group'][] = ['llm', 'semantic', 'synonyms', 'volume'];
    const groupedKeywords = groups.reduce((acc, group) => {
        acc[group] = keywordProposals.filter((kw) => kw.group === group);
        return acc;
    }, {} as Record<string, KeywordProposal[]>);

    const toggleGroup = (group: string) => {
        setCollapsedGroups((prev) => {
            const next = new Set(prev);
            if (next.has(group)) next.delete(group);
            else next.add(group);
            return next;
        });
    };

    const isGroupAllSelected = (group: KeywordProposal['group']) =>
        groupedKeywords[group]?.every((kw) => kw.selected);

    const handleGenerateBrief = async () => {
        if (selectedCount < 3 && !warningShown) {
            setWarningShown(true);
            return;
        }

        setError(null);
        setLoading(true);
        setStreaming(true);
        setBrief('');
        goToStep(4);

        abortRef.current = new AbortController();
        const selectedTexts = keywordProposals
            .filter((kw) => kw.selected)
            .map((kw) => kw.text);

        try {
            await generateBrief(
                config,
                selectedTexts,
                (chunk) => useAppStore.getState().appendBrief(chunk),
                abortRef.current.signal
            );

            // Save to history
            const brief = useAppStore.getState().brief;
            addToHistory({
                id: crypto.randomUUID(),
                title: config.title,
                model: model?.label || config.modelId,
                provider: config.provider,
                language: config.language,
                timestamp: new Date().toISOString(),
                content: brief,
                keywordCount: selectedCount,
            });
        } catch (err) {
            if (err instanceof DOMException && err.name === 'AbortError') return;
            setError(err as AppError);
        } finally {
            setLoading(false);
            setStreaming(false);
        }
    };

    return (
        <>
            {/* Selection toolbar */}
            <div className="selection-toolbar">
                <div className="selection-count">
                    <span className="count-badge">{selectedCount}</span>
                    <span>keywords selected</span>
                    {keywordProposals.length > 0 && (
                        <span style={{ color: 'var(--ink-3)', fontSize: '12px' }}>
                            of {keywordProposals.length} proposals · Generated by {model?.label}
                        </span>
                    )}
                </div>
                <div className="selection-actions">
                    <button className="btn btn-ghost" onClick={selectAllKeywords}>Select All</button>
                    <button className="btn btn-ghost" onClick={deselectAllKeywords}>Deselect All</button>
                </div>
            </div>

            {/* Warning for less than 3 keywords */}
            {warningShown && selectedCount < 3 && (
                <div className="error-banner warning" role="status" aria-live="polite">
                    <span className="error-icon">⚠️</span>
                    <div className="error-text">
                        <div className="error-title">Only {selectedCount} keyword{selectedCount !== 1 ? 's' : ''} selected</div>
                        <div className="error-message">
                            For a high-quality brief, we recommend at least 3 keywords. You can continue, but the result may be more generic.
                        </div>
                    </div>
                </div>
            )}

            {error && (
                <div className="error-banner error" role="alert" aria-live="assertive">
                    <span className="error-icon">⚠️</span>
                    <div className="error-text">
                        <div className="error-title">Error</div>
                        <div className="error-message">{error.message}</div>
                    </div>
                    <button className="error-dismiss" onClick={() => setError(null)}>✕</button>
                </div>
            )}

            {/* Keyword Groups */}
            <div className="keyword-groups">
                {groups.map((group) => {
                    const kws = groupedKeywords[group];
                    if (!kws || kws.length === 0) return null;
                    const colors = GROUP_COLORS[group];
                    const collapsed = collapsedGroups.has(group);
                    const allSelected = isGroupAllSelected(group);

                    return (
                        <div className="keyword-group" key={group}>
                            <div className="keyword-group-header" onClick={() => toggleGroup(group)}>
                                <div className="keyword-group-title">
                                    <span>{KEYWORD_GROUP_ICONS[group]}</span>
                                    <span
                                        className="keyword-group-badge"
                                        style={{ background: colors.bg, color: colors.color }}
                                    >
                                        {KEYWORD_GROUP_LABELS[group]} ({kws.length})
                                    </span>
                                </div>
                                <div className="keyword-group-actions" onClick={(e) => e.stopPropagation()}>
                                    <button
                                        className="btn btn-ghost"
                                        style={{ fontSize: '11px' }}
                                        onClick={() => allSelected ? deselectGroup(group) : selectGroup(group)}
                                    >
                                        {allSelected ? 'Deselect group' : 'Select group'}
                                    </button>
                                    <span style={{ color: 'var(--ink-3)', fontSize: '16px' }}>
                                        {collapsed ? '▸' : '▾'}
                                    </span>
                                </div>
                            </div>

                            {!collapsed && (
                                <div className="keyword-group-body">
                                    {kws.map((kw) => {
                                        const globalIndex = keywordProposals.indexOf(kw);
                                        return (
                                            <div
                                                key={globalIndex}
                                                className={`keyword-item ${kw.selected ? 'selected' : ''}`}
                                                onClick={() => toggleKeyword(globalIndex)}
                                                role="checkbox"
                                                aria-checked={kw.selected}
                                                aria-label={kw.text}
                                                tabIndex={0}
                                                onKeyDown={(e) => {
                                                    if (e.key === ' ') { e.preventDefault(); toggleKeyword(globalIndex); }
                                                }}
                                            >
                                                <div className="keyword-checkbox">{kw.selected ? '✓' : ''}</div>
                                                <div>
                                                    <div className="keyword-text">{kw.text}</div>
                                                    <div className="keyword-meta">
                                                        <span className={`volume-badge ${kw.volume}`}>
                                                            {VOLUME_LABELS[kw.volume]}
                                                        </span>
                                                    </div>
                                                    {kw.rationale && (
                                                        <div className="keyword-rationale">{kw.rationale}</div>
                                                    )}
                                                </div>
                                            </div>
                                        );
                                    })}
                                </div>
                            )}
                        </div>
                    );
                })}
            </div>

            {/* Footer */}
            <div className="step-footer" style={{
                position: 'sticky', bottom: '16px', background: 'var(--white)',
                padding: '16px 24px', borderRadius: 'var(--radius-lg)',
                boxShadow: 'var(--shadow-lg)', marginTop: 'var(--xl)',
                border: '1px solid var(--paper-2)'
            }}>
                <button className="btn btn-secondary" onClick={prevStep}>
                    ← Back
                </button>
                <button
                    className="btn btn-primary"
                    disabled={selectedCount === 0 || isLoading}
                    onClick={handleGenerateBrief}
                >
                    {isLoading ? (
                        <>
                            <span className="spinner" />
                            Generating Brief...
                        </>
                    ) : warningShown && selectedCount < 3 ? (
                        <>Continue anyway →</>
                    ) : (
                        <>Create Brief with {selectedCount} Keywords →</>
                    )}
                </button>
            </div>

            <div style={{ textAlign: 'center', fontSize: '11px', color: 'var(--ink-3)', marginTop: 'var(--md)' }}>
                💡 Volume estimates are AI-generated approximations, not real SEO tool data.
            </div>
        </>
    );
};
