import React, { useRef } from 'react';
import { useAppStore } from '../../store/useAppStore';
import { generateBrief } from '../../services/llm';
import { getModelById } from '../../config/models';
import { VOLUME_LABELS } from '../../types';
import type { AppError } from '../../types';

export const KeywordSelection: React.FC = () => {
    const {
        keywordProposals, toggleKeyword, setPrimaryKeyword, selectAllKeywords, deselectAllKeywords,
        config, prevStep,
        setBrief, setLoading, setStreaming, setError, setStep: goToStep,
        isLoading, error, addToHistory
    } = useAppStore();

    const abortRef = useRef<AbortController | null>(null);
    const model = getModelById(config.modelId);

    const selectedCount = keywordProposals.filter((kw) => kw.selected).length;

    const handleGenerateBrief = async () => {
        setError(null);
        setLoading(true);
        setStreaming(true);
        setBrief('');
        goToStep(4);

        abortRef.current = new AbortController();
        const primaryKw = keywordProposals.find(kw => kw.isPrimary);
        const secondaryKws = keywordProposals.filter(kw => kw.selected && !kw.isPrimary);

        try {
            await generateBrief(
                config,
                primaryKw?.text || null,
                secondaryKws.map(k => k.text),
                (chunk: string) => useAppStore.getState().appendBrief(chunk),
                abortRef.current.signal
            );

            // Save to history
            const brief = useAppStore.getState().brief;
            addToHistory({
                id: crypto.randomUUID(),
                title: config.title,
                model: model?.label || config.modelId,
                provider: config.provider,
                language: config.language,
                timestamp: new Date().toISOString(),
                content: brief,
                keywordCount: selectedCount,
            });
        } catch (err) {
            if (err instanceof DOMException && err.name === 'AbortError') return;
            setError(err as AppError);
        } finally {
            setLoading(false);
            setStreaming(false);
        }
    };

    return (
        <>
            {/* Selection toolbar */}
            <div className="selection-toolbar">
                <div className="selection-count">
                    <span className="count-badge">{selectedCount}</span>
                    <span>keywords selected</span>
                    {keywordProposals.length > 0 && (
                        <span style={{ color: 'var(--ink-3)', fontSize: '12px' }}>
                            of {keywordProposals.length} proposals · Generated by {model?.label}
                        </span>
                    )}
                </div>
                <div className="selection-actions">
                    <button className="btn btn-ghost" onClick={selectAllKeywords}>Select All</button>
                    <button className="btn btn-ghost" onClick={deselectAllKeywords}>Deselect All</button>
                </div>
            </div>

            {error && (
                <div className="error-banner error" role="alert" aria-live="assertive">
                    <span className="error-icon">⚠️</span>
                    <div className="error-text">
                        <div className="error-title">Error</div>
                        <div className="error-message">{error.message}</div>
                    </div>
                    <button className="error-dismiss" onClick={() => setError(null)}>✕</button>
                </div>
            )}

            {/* Keywords List */}
            <div className="keyword-list">
                {keywordProposals.map((kw, index) => (
                    <div
                        key={index}
                        className={`keyword-item ${kw.selected ? 'selected' : ''} ${kw.isPrimary ? 'primary' : ''}`}
                        onClick={() => toggleKeyword(index)}
                        role="checkbox"
                        aria-checked={kw.selected}
                        aria-label={kw.text}
                        tabIndex={0}
                        onKeyDown={(e) => {
                            if (e.key === ' ') { e.preventDefault(); toggleKeyword(index); }
                        }}
                    >
                        <div className="keyword-checkbox">
                            {kw.isPrimary ? '⭐' : (kw.selected ? '✓' : '')}
                        </div>

                        <div className="keyword-content" style={{ flex: 1, minWidth: 0 }}>
                            <div className="keyword-text-row" style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
                                <span className="keyword-text" style={{ fontWeight: 600, fontSize: '14px' }}>{kw.text}</span>
                                {kw.isPrimary && <span className="primary-badge">PRIMARY (70%)</span>}
                            </div>
                            <div className="keyword-meta">
                                <span className={`volume-badge ${kw.volume}`}>
                                    {VOLUME_LABELS[kw.volume]}
                                </span>
                            </div>
                            {kw.rationale && (
                                <div className="keyword-rationale">{kw.rationale}</div>
                            )}
                        </div>

                        <div className="keyword-actions" onClick={(e) => e.stopPropagation()} style={{ flexShrink: 0, marginLeft: '16px' }}>
                            {!kw.isPrimary && (
                                <button
                                    className="primary-select-btn"
                                    onClick={() => setPrimaryKeyword(index)}
                                    title="Set as Primary Topic"
                                >
                                    ⭐ Principal
                                </button>
                            )}
                        </div>
                    </div>
                ))}
            </div>

            {/* Footer */}
            <div className="step-footer" style={{
                position: 'sticky', bottom: '16px', background: 'var(--white)',
                padding: '16px 24px', borderRadius: 'var(--radius-lg)',
                boxShadow: 'var(--shadow-lg)', marginTop: 'var(--xl)',
                border: '1px solid var(--paper-2)'
            }}>
                <button className="btn btn-secondary" onClick={prevStep}>
                    ← Back
                </button>
                <button
                    className="btn btn-primary"
                    disabled={selectedCount === 0 || isLoading}
                    onClick={handleGenerateBrief}
                >
                    {isLoading ? (
                        <>
                            <span className="spinner" />
                            Generating Brief...
                        </>
                    ) : (
                        <>Create Brief with {selectedCount} Keywords →</>
                    )}
                </button>
            </div>

            <div style={{ textAlign: 'center', fontSize: '11px', color: 'var(--ink-3)', marginTop: 'var(--md)' }}>
                💡 Volume estimates are AI-generated approximations, not real SEO tool data.
            </div>
        </>
    );
};
